"""store all table

Revision ID: 8a4f7fcf6154
Revises: 0e6e77054033
Create Date: 2025-05-08 22:46:21.111774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a4f7fcf6154'
down_revision: Union[str, None] = '0e6e77054033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'user_choice',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('question', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.add_column('score', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'score')
    op.alter_column('question', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('question', 'user_choice',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
